apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    app.kubernetes.io/name: rag-playground
spec:
  replicas: {{ .Values.frontend.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: rag-playground
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rag-playground
    spec:
      {{- if .Values.imagePullSecret.name }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.name }}
      {{- end }}
      containers:
      - name: rag-playground
        imagePullPolicy: IfNotPresent
        image: {{ .Values.frontend.image }}
        command:
        - python3.10
        - -m
        - frontend
        - --port
        - {{ .Values.frontend.service.targetPort | quote }}
        env:
        {{- range .Values.frontend.env }}
          - name: {{ .name }}
            value: {{ .value | quote }}
        {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.frontend.service.targetPort }}
          protocol: TCP
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app.kubernetes.io/name: rag-playground
{{- with .Values.frontend.service.ports }}
  ports:
  {{- toYaml . | nindent 4 }}
{{- end }}
