services:
  evaluation:
    container_name: evaluation
    image: evalulation:latest
    build:
      context: ../../
      dockerfile: ./tools/evaluation/Dockerfile.eval
    ports:
    - "8889:8889"
    expose:
    - "8889"