# Default values for rag-llm-pipeline

imagePullSecret:
  # Leave blank, if no imagePullSecret is needed.
  registry: "nvcr.io"
  name: "ngc-secret"
  # If set to false, the chart expects either a imagePullSecret
  # with the name configured above to be present on the cluster or that no
  # credentials are needed.
  create: false
  username: '$oauthtoken'
  password: ""

query:
  image: nvcr.io/ea-botmaker/dev/chain-server:ai-foundation-rag-0.4.0-rc1
  replicas: 1
  resources:
    limits:
      nvidia.com/gpu: 1  # Number of GPUs to present to the running service
  nodeSelector: {}
  tolerations: {}
  affinity: {}
  env:
      APP_LLM_MODELNAME: mixtral_8x7b
      APP_LLM_MODELENGINE: nv-ai-foundation
      APP_EMBEDDINGS_MODELNAME: nvolveqa_40k
      APP_EMBEDDINGS_MODELENGINE: nv-ai-foundation
      APP_TEXTSPLITTER_CHUNKSIZE: 2000
      APP_TEXTSPLITTER_CHUNKOVERLAP: 200
      APP_PROMPTS_CHATTEMPLATE: "You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe. Please ensure that your responses are positive in nature."
      APP_PROMPTS_RAGTEMPLATE: "You are a helpful AI assistant named Envie. You will reply to questions only based on the context that you are provided. If something is out of context, you will refrain from replying and politely decline to respond to the user."
      APP_CONFIG_FILE: /dev/null
  service:
      type: ClusterIP
      targetPort: 8082
      ports:
        - port: 8082
          targetPort: http
          protocol: TCP
          name: http

frontend:
  image: nvcr.io/ea-botmaker/dev/llm-playground:0.4.0-rc1
  replicas: 1
  nodeSelector: {}
  tolerations: {}
  affinity: {}
  env:
    - name: APP_MODELNAME
      value: "mixtral_8x7b"
    - name: APP_SERVERPORT
      value: "8082"
    - name: APP_SERVERURL
      value: http://query-router
    - name: RIVA_API_URI
      value: ""
    - name: RIVA_API_KEY
      value: ""
    - name: RIVA_FUNCTION_ID
      value: ""
    - name: TTS_SAMPLE_RATE
      value: 48000
  service:
      type: NodePort
      targetPort: 8091
      ports:
        - port: 8091
          targetPort: http
          protocol: TCP
          name: http