apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: pgvector
  name: pgvector
spec:
  replicas: {{ .Values.pgvector.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: pgvector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pgvector
    spec:
      {{- if .Values.imagePullSecret.name }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.name }}
      {{- end }}
      containers:
        - env:
          {{- range .Values.pgvector.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          image: {{ .Values.pgvector.image }}
          name: pgvector
          ports:
            - name: http
              containerPort: {{ .Values.pgvector.service.targetPort }}
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data-store
          resources:
            {{- toYaml .Values.pgvector.resources | nindent 12 }}
      restartPolicy: Always
      {{- with .Values.pgvector.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pgvector.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pgvector.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data-store
          {{- if .Values.pgvector.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.pgvector.persistence.existingClaim | default "pgvector-pvc" }}
          {{- else if .Values.pgvector.hostPath.enabled }}
          hostPath:
            path: {{ .Values.pgvector.hostPath.path }}
            type: DirectoryOrCreate
          {{- else }}
          emptyDir: {}
          {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: pgvector
  name: pgvector
spec:
  type: {{ .Values.pgvector.service.type }}
{{- with .Values.pgvector.service.ports }}
  ports:
  {{- toYaml . | nindent 4 }}
{{- end }}
  selector:
    app.kubernetes.io/name: pgvector
